<?php

$title = 'Ajouter nouveau produit';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('produit', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('designation'));
?><br><?php
echo $this->formRow($form->get('prixUnitaire'));
?><br><?php
echo $this->formRow($form->get('quantite'));
?><br><?php
echo $this->formRow($form->get('tva'));
?><br><?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>